---
name: build ami
run-name: "build ami: ${{ github.ref_name }}"

on:
  workflow_dispatch:
    inputs:
      packer_log:
        description: PACKER_LOG
        type: choice
        options:
          - 0
          - 1
      skip_create_ami:
        type: boolean
      debug:
        type: boolean
      on_error_abort:
        description: on-error=abort
        type: boolean
      dump_context:
        type: boolean

jobs:
  build_ami:
    runs-on: ubuntu-latest
    name: build
    env:
      AWS_DEFAULT_REGION:    us-east-2
      AWS_REGION:            us-east-2
      AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: crazy-max/ghaction-dump-context@v2
        if: github.event.inputs.dump_context == true

      - uses: actions/checkout@v3

      - name: packer build
        run: |
          echo "packer $(packer --version)"
          echo "session-manager-plugin $(session-manager-plugin --version)"
          packer init .
          packer validate .
          params=()
          if [[ ${{ github.event.inputs.debug }} == true ]]; then
            params+=(-debug)
          fi
          if [[ ${{ github.event.inputs.on_error_abort }} == true ]]; then
            params+=(-on-error=abort)
          fi
          packer build "${params[@]}" .
        working-directory: ./packer
        env:
          PACKER_GITHUB_API_TOKEN:        ${{ github.token }}
          PACKER_LOG:                     ${{ github.event.inputs.packer_log }}
          PKR_VAR_aws_region_to_build_in: ${{ env.AWS_REGION }}
          PKR_VAR_aws_role_to_assume:     ${{ secrets.AWS_ROLE_TO_ASSUME }}
          PKR_VAR_github_branch:          ${{ github.ref_name }}
          PKR_VAR_github_repo:            ${{ github.repository }}
          PKR_VAR_skip_create_ami:        ${{ github.event.inputs.skip_create_ami }}
