---
name: build ami
run-name: build ami from branch ${{ github.ref_name }}

on:    # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      packer_log:
        description: PACKER_LOG
        type: choice
        default: 0
        required: true
        options:
          - 0
          - 1

jobs:
  build_ami:
    runs-on: ubuntu-latest
    name: build

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: config aws creds
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: packer build
        run: |
          packer --version
          packer init .
          packer validate .
          packer build .
        working-directory: ./packer
        env:
          PACKER_LOG: ${{ github.event.inputs.packer_log }}
          PKR_VAR_github_branch: ${{ github.ref_name }}
          PKR_VAR_github_repo: ${{ github.repository }}
