---
name: build ami
run-name: "build ami: ${{ github.ref_name }}"

on:
  workflow_dispatch:
    inputs:
      packer_log:
        description: PACKER_LOG
        type: choice
        options:
          - 0
          - 1
      skip_create_ami:
        type: boolean
      debug:
        type: boolean
      on_error_abort:
        description: on-error=abort
        type: boolean

jobs:
  build_ami:
    runs-on: ubuntu-latest
    name: build

    steps:
      - uses: actions/checkout@v3

      - name: config aws creds
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            us-east-2
          role-to-assume:        ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: verify aws session manager plugin
        run: session-manager-plugin --version

      - name: packer build
        run: |
          packer --version
          packer init .
          packer validate .
          params=()
          if [[ ${{ github.event.inputs.debug }} == true ]]; then
            params+=(-debug)
          fi
          if [[ ${{ github.event.inputs.on_error_abort }} == true ]]; then
            params+=(-on-error=abort)
          fi
          packer build "${params[@]}" .
        working-directory: ./packer
        env:
          PACKER_GITHUB_API_TOKEN: ${{ github.token }}
          PACKER_LOG:              ${{ github.event.inputs.packer_log }}
          PKR_VAR_github_branch:   ${{ github.ref_name }}
          PKR_VAR_github_repo:     ${{ github.repository }}
          PKR_VAR_skip_create_ami: ${{ github.event.inputs.skip_create_ami }}
