name: cleanup

on: 
  workflow_dispatch:
    inputs:
      dry_run:
        type: boolean
        default: false
        description: 'dry run'

jobs:
  cleanup_workflow_logs:
    runs-on: ubuntu-latest
    name: cleanup workflow logs
    steps:
      - name: cleanup workflow logs of 'build'
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          delete_workflow_pattern: build ami
          retain_days: 0
          keep_minimum_runs: 4
          dry_run: ${{ github.event.inputs.dry_run }}
      - name: cleanup workflow logs of 'linter'
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          delete_workflow_pattern: linter
          retain_days: 0
          keep_minimum_runs: 4
          dry_run: ${{ github.event.inputs.dry_run }}
      - name: cleanup workflow logs of 'cleanup'
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          delete_workflow_pattern: cleanup
          retain_days: 0
          keep_minimum_runs: 4
          dry_run: ${{ github.event.inputs.dry_run }}
