---
name: cleanup

on: workflow_dispatch    # yamllint disable-line rule:truthy

jobs:
  cleanup_workflow_logs:
    runs-on: ubuntu-latest
    name: cleanup workflow logs
    steps:
      - name: cleanup workflow logs of 'build'
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          delete_workflow_pattern: build ami
          retain_days: 0
          keep_minimum_runs: 10

      - name: cleanup workflow logs of 'linter'
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          delete_workflow_pattern: linter
          retain_days: 0
          keep_minimum_runs: 10

      - name: cleanup workflow logs of 'cleanup'
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          delete_workflow_pattern: cleanup
          retain_days: 0
          keep_minimum_runs: 10
