name: cleanup

on: workflow_dispatch

jobs:
  cleanup_workflow_logs:
    runs-on: ubuntu-latest
    name: cleanup workflow logs
    steps:
      - name: cleanup workflow logs of 'build'
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          delete_workflow_pattern: build
          retain_days: 0
          keep_minimum_runs: 2
          dry_run: true
