---
name: linter

on: [pull_request, workflow_dispatch]

jobs:
  packer_fmt:
    runs-on: ubuntu-latest
    name: packer fmt
    steps:
      - uses: actions/checkout@v3

      - name: packer fmt
        run: |
          packer --version
          packer fmt -check -diff -recursive .
        working-directory: ./packer

  terraform_fmt:
    runs-on: ubuntu-latest
    name: terraform fmt
    steps:
      - uses: actions/checkout@v3

      - name: terraform fmt
        run: |
          terraform --version
          terraform fmt -check -diff -recursive .
        working-directory: ./terraform

  yamllint:
    runs-on: ubuntu-latest
    name: yamllint
    steps:
      - uses: actions/checkout@v3

      - name: yamllint
        run: |
          yamllint --version
          yamllint --list-files ./.github/workflows
          yamllint --strict ./.github/workflows
