---
name: linter

on: [pull_request, workflow_dispatch]    # yamllint disable-line rule:truthy

jobs:
  packer_linter:
    runs-on: ubuntu-latest
    name: packer linter
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: packer linter
        run: |
          packer --version
          packer fmt -check -diff -recursive .
        working-directory: ./packer

  terraform_linter:
    runs-on: ubuntu-latest
    name: terraform linter
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: terraform linter
        run: |
          terraform --version
          terraform fmt -check -diff -recursive .
        working-directory: ./terraform

  yaml_linter:
    runs-on: ubuntu-latest
    name: yaml linter
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: yaml linter
        run: |
          yamllint --version
          yamllint --strict .
        working-directory: ./.github/workflows
