---
name: linter

on: [pull_request, workflow_dispatch]    # yamllint disable-line rule:truthy

jobs:
  packer_fmt:
    runs-on: ubuntu-latest
    name: packer fmt
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: packer fmt
        run: |
          packer --version
          packer fmt -check -diff -recursive .
        working-directory: ./packer

  terraform_fmt:
    runs-on: ubuntu-latest
    name: terraform fmt
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: terraform fmt
        run: |
          terraform --version
          terraform fmt -check -diff -recursive .
        working-directory: ./terraform

  yamllint:
    runs-on: ubuntu-latest
    name: yamllint
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: yamllint
        run: |
          yamllint --version
          yamllint --strict .
        working-directory: ./.github/workflows
